// Code generated by Slice Machine. DO NOT EDIT.

import Caracteristicas from './Caracteristicas';
import HistoriasReales from './HistoriasReales';
import PerfilSanitario from './PerfilSanitario';
import SliderHome from './SliderHome';
import TabsTech from './TabsTech';
import TrigoDescription from './TrigoDescription';

export {
	Caracteristicas,
	HistoriasReales,
	PerfilSanitario,
	SliderHome,
	TabsTech,
	TrigoDescription,
};

export const components = {
	caracteristicas: Caracteristicas,
	historias_reales: HistoriasReales,
	perfil_sanitario: PerfilSanitario,
	slider_home: SliderHome,
	tabs_tech: TabsTech,
	rich_text: TrigoDescription,
};
